version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing npm dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the React app..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed!"
      - aws s3 cp build/ s3://portfolio-ayushi/ --recursive

artifacts:
  files:
    - **/*
  base-directory: build
