version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing npm dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the React app..."
      - npm run build

artifacts:
  base-directory: build
  files:
    - '**/*'
